### ISSUE TITLE
Migrate to EC2

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/scholarx#117]
**Is your feature request related to a problem? Please describe.**
Limitations of Heroku is problematic for a lot of deployments.

**Describe the solution you'd like**
Use a AWS EC2 Ubuntu VPS for the deployments.

**Related Issue**
https://github.com/sef-global/scholarx-frontend/issues/93

**Comment by Piumal1999** [comment]
Closing this issue because of the cpu credit issue of EC2 Instance. We can reopen the issue later if needed
