### ISSUE TITLE
Write a unit test for getAllMenteesByProgramId method

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#128]
**Is your feature request related to a problem? Please describe.**
- We need to write unit tests getAllMenteesByProgramId method.

**Describe the solution you'd like**
- Write the relevant unit tests

**Comment by posabogdanpetre** [comment]
@anjula-sack I can help here. Can you please assign me?

**Comment by anjula-sack** [comment]
> @anjula-sack I can help here. Can you please assign me?

sure

**Comment by posabogdanpetre** [comment]
@anjula-sack Just opened a PR. Can you please help me with a review?
