### ISSUE TITLE
Update README file 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx#131]
**Is your feature request related to a problem? Please describe.**
The current readme file is outdated and needs to be updated

**Describe the solution you'd like**
Update the readme file with the new setup instructions

**Comment by Madhawa97** [comment]
shall I work on this?

**Comment by Piumal1999** [comment]
I think this issue is already completed with 190a89c1c3ad72ed0db194ca7a82afd700d78f5a. If there's anything missing in the Readme file, you can create a Pull request and mention this issue.

**Comment by Madhawa97** [comment]
sure 👍🏻

**Comment by Piumal1999** [comment]
Fixed with #210 and 190a89c
