### ISSUE TITLE
Improving the architecture of emailing feature

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/scholarx#134]
**Is your feature request related to a problem? Please describe.**
Emailing functionality is covered under the `EmailUtil` class, this should be avoided due to following reasons,
1. Util classes shouldn't instantiate instance vars or contain instance methods
2. `JavaMailSender` is a service. 

**Describe the solution you'd like**
Create a new service with a `@autowired` instance variable of `JavaMailSender` with a function to send an email. Then inject the new class to required services and call the function to send any required mails.

**Additional context**
Also it would be nice to move the current switch case used in `ProgramService` to send bulk mails into a new method inside the same service

**Comment by DilshanNaveen** [comment]
@YohanAvishke,  I like to work on this 😃️

**Comment by jayasanka-sack** [comment]
Hi @DilshanNaveen,
Any luck on this?

**Comment by Gravewalker666** [comment]
Closed with #150
