### ISSUE TITLE
Updating the travis before_script 

### ISSUE THREAD

**Issue by kumuditha-udayanga** [sef-global/scholarx#161]
**Describe the bug**
We don’t need a dist directory anymore.

**To Reproduce**
- Remove `/dist` part.

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser: Safari
 - Version: 14.0.1

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, I would like to work on this issue :)

**Comment by anjula-sack** [comment]
sure go ahead
