### ISSUE TITLE
Users with new linkedin accounts can't sign in

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#183]
**Describe the bug**
- The login is crashing for new linkedin users

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the homepage
2. Click on sign in
3. Create a new account without the profile picture
4. See the error

**Expected behaviour**
- All LinkedIn users need to be able to log in without error

**Desktop (please complete the following information):**
 - OS: Big Sur 11.4
 - Browser : Chrome

**Comment by cmdrGuyson** [comment]
Please assign me to this issue.
