### ISSUE TITLE
Admin API : Delete a Program

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/scholarx#19]
**Is your feature request related to a problem? Please describe.**
We need an admin endpoint to delete a program.

**Describe the solution you'd like**
https://documenter.getpostman.com/view/8545501/T1LLFTrx?version=latest#18508655-0b56-497e-95b5-d60d906b7db9

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Piumal1999** [comment]
@YohanAvishke Are you working on this? If not, i can resolve this issue with PR #25
