### ISSUE TITLE
Add mentor details columns to the mentor table

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#218]
**Is your feature request related to a problem? Please describe.**
For the February edition of scholarx, we are adding a few more questions to the mentor application. And we need to store the responses in the mentor table.

**Describe the solution you'd like**
Add the following fields to the Mentor Model

1. Category (category)
2. Area(s) of Expertise (expertise)
3. Institution (institution)
4. Position (position)
5. Bio (bio)
6. No. of Mentee Slots (slots)

https://sef.discourse.group/t/scholarx-february-edition/359/11?u=piumal1999

**Describe alternatives you've considered**
N/A

**Additional context**
We can keep categories as enums too. But for that, we'll need to define the categories we have. (Engineering, Life Sciences, Computer Science, Data Science & AI, Physical Science, Other)

**Comment by Gimhan-minion** [comment]
Shall I work on this? @Piumal1999

**Comment by Piumal1999** [comment]
Yeah sure @Gimhan-minion
