### ISSUE TITLE
Remove confirmMentor endpoint and service method

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#223]
**Is your feature request related to a problem? Please describe.**
We don't need the mentor confirmation endpoint since the February edition doesn't have the mentor confirmation state.

**Describe the solution you'd like**
Remove the /api/me/mentor/{id}/confirmation endpoint. (`src/main/java/org/sefglobal/scholarx/controller/AuthUserController.java`)
Remove the respective service method

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Gimhan-minion** [comment]
Shall i work on this? @Piumal1999

**Comment by Piumal1999** [comment]
@Gimhan-minion Also remove the things related to the MENTOR_CONFIRMATION State.
1. Enum
2. Code used for removing mentees who haven't confirmed the mentors (src/main/java/org/sefglobal/scholarx/service/ProgramService.java:updateState)
   ```
        final ProgramState nextState = program.get().getState().next();
        if (ProgramState.ONGOING.equals(nextState)) {
            List<Mentee> approvedMenteeList = menteeRepository.findAllByProgramIdAndState(id, EnrolmentState.APPROVED);
            for (Mentee mentee : approvedMenteeList) {
                long profileId = mentee.getProfile().getId();
                if (menteeRepository.findAllByProgramIdAndProfileIdAndState(id, profileId, EnrolmentState.APPROVED).size() != 1) {
                    menteeRepository.removeAllByProgramIdAndProfileId(id, profileId);
                }
            }
   ```
3. `/api/me/mentor/{id}/confirmation` endpoint
