### ISSUE TITLE
Prevent mentees from applying for the same program twice

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#227]
**Is your feature request related to a problem? Please describe.**
In the sx-february edition, we are not allowing mentees to apply for multiple mentors

**Describe the solution you'd like**
Validate the related endpoint:
`applyAsMentee` in `src/main/java/org/sefglobal/scholarx/service/MentorService.java`

**Describe alternatives you've considered**
N/A

**Additional context**
You can update this code segment to solve the issue
```
        Optional<Mentee> duplicateMentee = menteeRepository.findByProfileIdAndAppliedMentorId(profileId, mentorId);
        if (duplicateMentee.isPresent()) {
            String msg = "Error, Unable to apply as a mentee. " +
                         "Profile with id: " + profileId + " has already applied for the selected mentor.";
            log.error(msg);
            throw new BadRequestException(msg);
        }
```

**Comment by cnonnet** [comment]
Hello, I would like to try to solve this issue, could you assigned me ?

**Comment by Piumal1999** [comment]
Yeah @cnonnet, sure! Let us know when you have started working on the issue. If you have any problems, feel free to contact us through our [slack channel ](https://join.slack.com/t/sefheadquarters/shared_invite/zt-9w6v9rdu-uJGLrMKLTNFzQEVPC4sbOw) or [SEF Hive](https://sef.discourse.group/)
