### ISSUE TITLE
Mentors should be able to update all fields using applyAsMentor endpoint

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#228]
**Is your feature request related to a problem? Please describe.**
After adding the new columns to the mentor table, we forgot to update the applyAsMentor endpoint to get and set those new data

**Describe the solution you'd like**
Update the `src/main/java/org/sefglobal/scholarx/service/ProgramService.java:applyAsMentor` method to set the following fields.
1. category
2. expertise
3. institution
4. position
5. bio
6. slots

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Madhawa97** [comment]
Can I work on this?
