### ISSUE TITLE
Update 'Get my applied mentors' endpoint to return only 1 mentor

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#229]
**Is your feature request related to a problem? Please describe.**
In sx-february edition, we are not allowing mentees to apply for multiple mentors. So we don't need to return a list of mentors when mentees check their applied mentor.

**Describe the solution you'd like**
1. Change the method names(controller-`getAppliedMentor`, service-`getAppliedMentorOfMentee`)
2. Remove the menteeState path param
3. Use the `findByProgramIdAndProfileId` repository method to get the mentee object
4. Throw `NoContentException` if the mentee doesn't exist
5. Return the mentee
6. Update the unit tests

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bahadirkaratas** [comment]
Hi @Piumal1999, 

I would like to try working on this, could you assign it to me?
