### ISSUE TITLE
Mentor Application

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/scholarx#231]
- [x] **Backend:**
    - [x] Update Apply as Mentor Endpoint
        - [x] #215
        - [x] #218  
        - [x] #228
    - [x] #242
- [x]  **Frontend:**
    - [x] https://github.com/sef-global/scholarx-frontend/issues/270
    - [x] https://github.com/sef-global/scholarx-frontend/issues/272

**Comment by Piumal1999** [comment]
The core functionality is completed
