### ISSUE TITLE
Mentee Application

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/scholarx#233]
- [x] **Backend:**
    - [x] New enrolment states
        - [x] #246
        - [x] #255
    - [x] Update Apply as Mentee Endpoint + Edit Mentee Application Endpoint
        - [x] #219
        - [x] #227 
    - [x] Get My Mentee Applications
        - [x]  #229 
        - [x]  #264 
        - [x]  #266 
        - [x]  #267 
        - [x]  #269 
- [x]  **Frontend:**
    - [x] https://github.com/sef-global/scholarx-frontend/issues/257
    - [x] https://github.com/sef-global/scholarx-frontend/issues/276
    - [x] https://github.com/sef-global/scholarx-frontend/issues/281
    - [x] https://github.com/sef-global/scholarx-frontend/issues/286

**Comment by Piumal1999** [comment]
Completed
