### ISSUE TITLE
Create an admin endpoint to change mentee states

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#243]
**Is your feature request related to a problem? Please describe.**
Admins should be able to change the state of mentees.

**Describe the solution you'd like**
Create an admin endpoint for changing mentee states. Do the necessary validations(program state validations)
Endpoint: `PUT /api/admin/mentees/{id}/state`
Request Body: `Map<String, EnrolmentState>` (json object with attribute called "state")
Response: `Mentee`

Controller file: `src/main/java/org/sefglobal/scholarx/controller/admin/MenteeController.java`
Service file: `src/main/java/org/sefglobal/scholarx/service/MenteeService.java`

Discuss with the team to find the necessary validations.

**Describe alternatives you've considered**
N/A

**Additional context**
Add the relevant unit tests if possible
You can refer the `updateState` method in `controller/admin/MentorController.java`

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 I would like to work on this issue.

**Comment by Piumal1999** [comment]
Validations:

1. Throw BadRequestException if the state is 'REJECTED', 'APPROVED'
   - Because only mentors can reject/approve mentees. ([Hive post](https://sef.discourse.group/t/scholarx-february-edition/359/2?u=piumal1999))
2. Throw BadRequestException if the program state is **not** `ADMIN_MENTEE_FILTRATION` or `WILDCARD`

These are optional, but better to have.
