### ISSUE TITLE
Update Program State column length

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#253]
**Is your feature request related to a problem? Please describe.**
The program state column should be able to have data with 25 characters

**Describe the solution you'd like**
Update the Program State column length to 25.
Related File: `src/main/java/org/sefglobal/scholarx/model/Program.java`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 99sumedha** [comment]
@Piumal1999, Kindly assign me this issue ☺️
