### ISSUE TITLE
Add 'REMOVED' EnrolmentState to the Eligible Mentor States

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#257]
**Is your feature request related to a problem? Please describe.**
Mentees can have the `REMOVED` enrolment state. So admins should be able to change the mentor's state to `REMOVED` state

**Describe the solution you'd like**
Add `REMOVED` enrolment state to `eligibleEnrolmentStatesForMentors` list in `src/main/java/org/sefglobal/scholarx/service/MentorService.java`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Madhawa97** [comment]
Can you assign me?
