### ISSUE TITLE
Mentees should be able to change the applied Mentor

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#266]
**Is your feature request related to a problem? Please describe.**
A mentee can have only one application per program. Mentees should be able to change their primary mentor. But in the current backend, we use `PUT /api/mentors/{id}/mentee` to edit mentee application. But when using that, mentees can't change the appliedMentee because mentorId is in that endpoint as a path paramenter

**Describe the solution you'd like**
Update `PUT /api/mentor/{id}/mentee` endpoint to `PUT /api/program/{id}/mentee`
- Move the `updateMenteeData` method on MentorController.java to ProgramController.java

- Move `updateMenteeData` method on MentorService.java to ProgramService.java
  -  change `mentorId` parameter to `programId`
  - use `menteeRepository.findByProgramIdAndProfileId` to get the optionalMentee object
  - Update the relevant comments and error messages
  - The method should set the assignedMentor too (currently it only updates course,intent,university etc.)

- Move the relavant unit tests

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pasindur99** [comment]
@Piumal1999 I would like to work on this issue.
