### ISSUE TITLE
Mentee count does not change properly when changing mentee states

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#284]
**Describe the bug**
When admin changes the mentee state of a ASSIGNED Mentee, the assignedMentor becomes null. But in the current implementation it doesn't reduce 1 from the mentor's menteeCount in that scenario.

**To Reproduce**
1. Change the state of a ASSIGNED mentee

**Expected behavior**
If the mentee's previous state is ASSIGNED, reduce the menteeCount of previous mentor by 1

**Screenshots**
N/A

**Additional context**
N/A

**Comment by YaiyaSam** [comment]
can I work on this?

**Comment by Piumal1999** [comment]
> can I work on this?

Yeah @YaiyaSam . Go ahead
