### ISSUE TITLE
Missing space in selected mentee email 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#287]
**Describe the bug**
- There's a missing space in the mentee email where the mentor name is shown.

**To Reproduce**
Become a selected mentee,
1. Go to your inbox
2. Click on the mail
3. See the missing space

**Expected behavior**
- Proper spacings should be there on the emails

**Screenshots**
![image](https://user-images.githubusercontent.com/43912578/149648680-7b2d5e5b-fcc0-48e0-a75e-d19c7ae2fe4c.png)
![image](https://user-images.githubusercontent.com/43912578/149648687-950c22e9-e766-4904-a1db-41c3c2d1f08e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monteray
 - Browser: Chrome

**Comment by akeel230** [comment]
shall I work on this?

**Comment by anjula-sack** [comment]
> shall I work on this?

sure
