### ISSUE TITLE
Increase the column sizes of mentee/mentor applications

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#289]
**Is your feature request related to a problem? Please describe.**
Currently, the default character limit of all the fields in the mentee application is 255. But some fields need much larger character limit.

**Describe the solution you'd like**
Increase the column size of reasonForChoice, IntentForMentor columns to 500
Increase the column size of bio column to 500

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Gravewalker666** [comment]
Both on mentee and mentor applications

**Comment by Piumal1999** [comment]
> Both on mentee and mentor applications

Right. Are 500 characters enough for those columns?

**Comment by Gravewalker666** [comment]
Nope, Can we put the standard lengths from text or long text?
