### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/scholarx#32]
**Describe the bug**
Travis build fails when decrypting the private key.

**To Reproduce**
1. Go to https://travis-ci.org/github/sef-global/scholarx/builds/725475635
2. Click on `Restart build`

**Expected behavior**
Build should pass with successful web app deployment

**Screenshots**
![image](https://user-images.githubusercontent.com/36471249/92614452-b2371200-f2d9-11ea-8610-dac20332b260.png)
[Stacktrace](https://travis-ci.org/github/sef-global/scholarx/builds/725475635)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Piumal1999** [comment]
Closing the issue since it's outdated
