### ISSUE TITLE
Implement a mechanism to save the sending emails to the database

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx#325]
**Definition of done**
There is a table in the database the administrators can check as an email log that contains all of the automatic and custom emails sent through the platform 

**Addition information**
In addition to the common data attributes of the email, 
- The program id
- The program state in which the email was sent
- The time it was sent out

Should also be recorded

**Comment by YaiyaSam** [comment]
@Piumal1999 Hey, have you started working on this yet?

**Comment by Piumal1999** [comment]
> @Piumal1999 Hey, have you started working on this yet?

Not yet. Would you like to work on this?

**Comment by YaiyaSam** [comment]
> > @Piumal1999 Hey, have you started working on this yet?
> 
> Not yet. Would you like to work on this?

Yeah, I would like to give it a shot

**Comment by Piumal1999** [comment]
> > > @Piumal1999 Hey, have you started working on this yet?
> > 
> > 
> > Not yet. Would you like to work on this?
> 
> Yeah, I would like to give it a shot

Awesome
