### ISSUE TITLE
Replace the current email sender with simple java mail 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx#333]
**Is your feature request related to a problem? Please describe.**
The current email sender stops working after about 85 emails, throwing a too many login attempts error. 

**Describe the solution you'd like**
1. Replace the current email sender with simple java mail 
2. Make the smtp connection singleton 
3. Use the same connection to send out all of the emails 

Link: https://www.simplejavamail.org/

**Comment by pasindur99** [comment]
I will work on this issue.
