### ISSUE TITLE
Write a new deploy script to use Heroku CLI

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx#334]
**Is your feature request related to a problem? Please describe.**
Heroku doesn't provide the automated GitHub connect anymore and we need to update out GitHub actions for automated depolyment

**Describe the solution you'd like**
Write a script to be run on every push to the deploy branch (sx-feb-demo??) that would set up Heroku cli and deploy

**Comment by Piumal1999** [comment]
Closing since we no longer use Heroku
