### ISSUE TITLE
Create an API to update the details

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#346]
**Is your feature request related to a problem? Please describe.**
- We need an API to update the user details. 

**Describe the solution you'd like**
- Create an API to update the details - email, name, profile picture URL
- Create a field in the database to store the user detail confirmation. This will be a boolean `hasConfirmedUserDetails` which is going to be a field in the payload alongside the user details

**Comment by kumuditha-udayanga** [comment]
I would like to work on this @anjula-sack
