### ISSUE TITLE
Update the getLoggedInUser endpoint to get details from database

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#353]
**Is your feature request related to a problem? Please describe.**
Currently, when the getLoggedInUser endpoint is called, it gets the profile object from the session. But the session doesn't get updated if we change any profile detail while the user is logged in.

**Describe the solution you'd like**
Update the endpoint to get the profile from the DB. But add some validations to prevent any drawbacks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 I would like to work on this
