### ISSUE TITLE
Allow requests from scholarx.sefglobal.org origin

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#365]
**Is your feature request related to a problem? Please describe.**
The application throws a CORS error when using POST requests through scholarx.sefglobal.org origin

**Describe the solution you'd like**
Add the `https://scholarx.sefglobal.org` origin to this immutable origin list
https://github.com/sef-global/scholarx/blob/2e80ebd5541d903d6e58a8535e441494a2c3e914/src/main/java/org/sefglobal/scholarx/config/SecurityConfig.java#L100

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on it?**
No

**Comment by chirandevinda** [comment]
I would like to do this. can I?

**Comment by Piumal1999** [comment]
Sure, assigned @chirandevinda.
