### ISSUE TITLE
Update the emails templates

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#382]
**Is your feature request related to a problem? Please describe.**
- We need to update some emails templates

**Describe the solution you'd like**
- Update the following email templates

**Mentee Rejection Mail**

> Dear [Applicant Name],
> We wanted to take a moment to thank you for your interest in the ScholarX program and for submitting your application. We appreciate the time and effort you put into it.
> After a careful review of your application and considering all of the candidates, we regret to inform you that we are unable to offer you admission at this time. We received a large number of qualified applicants, and unfortunately, we could only accept a limited number of students.
> However, we want to encourage you not to be discouraged by this decision. We recognize that the admissions process can be competitive, and we understand that this news may be disappointing. Please know that this does not reflect on your abilities, potential, or value as an individual.
> We do offer the possibility for you to apply again next year if you meet the eligibility criteria. We invite you to stay engaged with us by attending our events, reaching out to our admissions team, and taking advantage of any opportunities to connect with our current students and alumni.
> Thank you again for considering our program and for the time you invested in your application. We wish you all the best in your future endeavours.
> Sincerely,
> [Your Name]
> 

**Mentee Acceptance Email**

> Dear [Applicant Name],
> We are delighted to inform you that you have been selected for our undergraduate program, and we extend our heartfelt congratulations to you!
> We received a large number of qualified applicants, and after a thorough review of all candidates, we are thrilled to offer you a place in our program. Your application stood out amongst the others, and we are confident that you will contribute positively to our program.
> We believe that you have great potential to succeed in your academic and professional pursuits, and we are excited to have you join our community of learners and scholars.
> To emphasize the importance of completing the program, you have received a valuable opportunity. If, for any reason, you are uncertain about completing the program within the 6-month timeline, please inform our admissions team as soon as possible, so we can provide the opportunity to another deserving student.
> Once again, congratulations on your selection! We cannot wait to have you on board.
> Best regards,
> [Your Name]

**Additional context**
- Double-check the spacings of the content

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by chirandevinda** [comment]
Can I do this?

**Comment by YoshithaRathnayake** [comment]
> Can I do this?

Please I'll work on this bcs I haven't done any work in these days @chirandevinda

**Comment by anjula-sack** [comment]
> > Can I do this?
> 
> Please I'll work on this bcs I haven't done any work in these days @chirandevinda

@YoshithaRathnayake This is urgent. @chirandevinda has done this before as well. You can work on another issue.

**Comment by anjula-sack** [comment]
> Can I do this?

Go ahead @chirandevinda
