### ISSUE TITLE
Update the mentor email template

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx#384]
**Is your feature request related to a problem? Please describe.**
- We need to update one of the emails

**Describe the solution you'd like**
- Update the string in the line 
https://github.com/sef-global/scholarx-backend-v1/blob/b8a7274c1510532f3fcfc232f48137ea6db2cb3c/src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java#LL126C15-L126C15
- Update the date to 26th May
- Add the following as another listed item.

> We would like to emphasize that some of the content in the mentee applications might be generated by an AI. While we have made efforts to ensure the quality and relevance of the generated content, we recommend reviewing the applications carefully to evaluate the mentees' suitability for the program.

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
I would like to work on this.
