### ISSUE TITLE
Mentee API - Get applied mentors

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#41]
Is your feature request related to a problem? Please describe.
We need a mentee endpoint to get the list of applied mentors

Describe the solution you'd like
Documentation: https://documenter.getpostman.com/view/8545501/T1LLFTrx?version=latest#e116ce69-5fa2-47c5-a33e-28ffc8f3bf63

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by Gravewalker666** [comment]
Working on it

**Comment by Gravewalker666** [comment]
Passed on the work to @YohanAvishke
