### ISSUE TITLE
Mentee API - Apply for Mentor

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#42]
Is your feature request related to a problem? Please describe.
We need a mentee endpoint to apply for mentors

Describe the solution you'd like
Documentation: https://documenter.getpostman.com/view/8545501/T1LLFTrx?version=latest#fcb3d7df-7d88-4e4c-8a13-d5ed8ace591f

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by Gravewalker666** [comment]
Working on it

**Comment by Gravewalker666** [comment]
Passed on the work to @YohanAvishke

**Comment by Piumal1999** [comment]
Duplicate of #37
