### ISSUE TITLE
Mentee API - Edit mentee application

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#43]
Is your feature request related to a problem? Please describe.
We need a mentee endpoint to edit mentee application

Describe the solution you'd like
Documentation: https://documenter.getpostman.com/view/8545501/T1LLFTrx?version=latest#dec99bfb-5ed0-46fe-a961-35a24a783b20

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by Gravewalker666** [comment]
I'm working on this

**Comment by Gravewalker666** [comment]
Passed on the work to @YohanAvishke
