### ISSUE TITLE
Mentee API - Get the selected mentor

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#44]
Is your feature request related to a problem? Please describe.
We need a mentee endpoint to get the selected mentors for the mentee

Describe the solution you'd like
Documentation: https://documenter.getpostman.com/view/8545501/T1LLFTrx?version=latest#28a47500-90df-49ee-a761-d368a59ebedf

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by Gravewalker666** [comment]
I'm working on this

**Comment by Gravewalker666** [comment]
Passed on the work to @YohanAvishke
