### ISSUE TITLE
Infinite loop in GET mentors API

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#48]
**Describe the bug**
An infinite loop is running when /program/{id}/mentors/ endpoint is called.

**To Reproduce**
1. Check the endpoint
2. See error

**Expected behavior**
Load the data without bugs

**Screenshots**
![Screenshot from 2020-10-03 22-40-46](https://user-images.githubusercontent.com/27498587/94999035-0630d000-05d4-11eb-8f24-794e1a11ba92.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A

**Additional context**
N/A

**Comment by YohanAvishke** [comment]
ignore comment
