### ISSUE TITLE
Update methods for program state creation & edition

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#53]
**Describe the bug**
The state should not send as a parameter when **creating**/**editing the state** of a program.

**To Reproduce**
1. Create a request to add/edit state APIs with a state param
2. Program is created or updated by the passed param.

**Expected behavior**
* When creating a state should always be CREATED
* When editing the state, it should be changed to the next existing one.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 81

**Additional context**
Update the test cases.

**Comment by Piumal1999** [comment]
I'm working on this

**Comment by YohanAvishke** [comment]
Hi @Piumal1999, We had a discussion about this I have already fixed this. Keep the issue I will send a PR

**Comment by Piumal1999** [comment]
Ah alright
