### ISSUE TITLE
Validate the body of create program endpoint

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#54]
**Is your feature request related to a problem? Please describe.**
The request body isn’t validated.
 ex: throws 500 when a not null field is not available in the body

**Describe the solution you'd like**
Ex:
If the landing page URL or image URL is not in the body, it adds a null value for them. It should return a bad request.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jayasanka-sack** [comment]
Hi piumal, thanks for creating the issue. 
This would be not a priority for our initial implementation. Let's move this task to a next phase.
