### ISSUE TITLE
Add a JSON response payload to DELETE endpoints

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#58]
**Is your feature request related to a problem? Please describe.**
We need to have a json response payload for all DELETE API endpoints for frontend usages

**Describe the solution you'd like**
Add a JSON response payload

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cmdrGuyson** [comment]
Shall I work on this?

**Comment by Piumal1999** [comment]
Hi @cmdrGuyson 
We are happy to hear from such enthusiastic developers like you. Unfortunately this issue is outdated, so fixing this may break the frontend. Sorry for any inconvenience caused.

Btw, you can try these issues.
https://github.com/sef-global/scholarx/issues/94
https://github.com/sef-global/scholarx/issues/95

Also you can contact us via the slack channel to get more info about the issues.
