### ISSUE TITLE
Update the endpoints to get profile id from the session

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#72]
**Is your feature request related to a problem? Please describe.**
For user APIs, we need to get the user's profile from the session

**Describe the solution you'd like**
Get the profileId from a cookie

**Describe alternatives you've considered**
N/A

**Additional context**
Hive thread:
https://sef.discourse.group/t/creating-mock-user-apis/207?u=piumal1999

**Comment by Piumal1999** [comment]
Some of the endpoints were missed in the pull request. So I'm reopening this

**Comment by YohanAvishke** [comment]
What are the missing endpoints?

**Comment by Piumal1999** [comment]
1. Update mentee data
2. Get logged in mentor
3. Get applied mentors of mentee
4. Get selected mentor of mentee

@CookieValue annotations were missed in these endpoints
