### ISSUE TITLE
Swagger UI throws 404 error

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx#93]
**Describe the bug**
Swagger UI doesn't work and throws 404 error.

**To Reproduce**
1. Go to '/api/scholarx/swagger-ui.html'
2. See error

**Expected behavior**
Swagger UI displaying the API details

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Browser [e.g. chrome, safari] Google Chrome

**Additional context**
The error occurred after adding the WebConfig file

**Comment by YohanAvishke** [comment]
This occurs due to the `WebConfig.java` file's configuration 
```java
public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**")
        .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT", "DELETE", "GET", "POST")
                .allowCredentials(true)
                .maxAge(3600);
    }
```
I think this is an temporary config added by @anjula-sack.
